services:
    Asdoria\SyliusBulkEditPlugin\Form\Type\Configuration\TaxonsConfigurationType:
        arguments:
            $taxonsToCodesTransformer: '@sylius.form.type.data_transformer.taxons_to_codes'
        tags:
            - { name: form.type }

    Asdoria\SyliusBulkEditPlugin\Form\Type\Configuration\TaxonConfigurationType:
        arguments:
            $taxonToCodeTransformer: '@Asdoria\SyliusBulkEditPlugin\Form\DataTransformer\TaxonToCodeTransformer'
        tags:
            - { name: form.type }
                
    Asdoria\SyliusBulkEditPlugin\Form\Type\Configuration\AttributeValueConfigurationType:
        arguments:
            $attributeChoiceType: 'Sylius\Bundle\ProductBundle\Form\Type\ProductAttributeChoiceType'
            $attributeRepository: '@sylius.repository.product_attribute'
            $localeRepository: '@sylius.repository.locale'
            $formTypeRegistry: '@sylius.form_registry.attribute_type'
        tags:
            - { name: form.type }                
                
    Asdoria\SyliusBulkEditPlugin\Form\Type\Configuration\TaxCategoryConfigurationType:
        arguments:
            $taxCategoryRepository: '@sylius.repository.tax_category'
        tags:
            - { name: form.type }
                
    Asdoria\SyliusBulkEditPlugin\Form\Type\Configuration\ShippingCategoryConfigurationType:
        arguments:
            $shippingCategoryRepository: '@sylius.repository.shipping_category'
        tags:
            - { name: form.type }
                
    Asdoria\SyliusBulkEditPlugin\Form\Type\Configuration\AttributeConfigurationType:
        arguments:
            $attributeRepository: '@sylius.repository.product_attribute'
        tags:
            - { name: form.type }

    Asdoria\SyliusBulkEditPlugin\Form\Type\Filter\AttributeValueStringFilterType:
        calls:
            - ['setLocaleContext', ['@sylius.context.locale']]
        tags:
            - { name: form.type }

    Asdoria\SyliusBulkEditPlugin\Form\Type\Configuration\AssociationsConfigurationType:
        arguments:
            $productRepository: '@sylius.repository.product'
            $productAssociationTypeRepository: '@sylius.repository.product_association_type'
        tags:
            - { name: form.type }
 
    Asdoria\SyliusBulkEditPlugin\Form\Type\BulkEditType:
        arguments:
            $formTypeRegistry: '@asdoria_bulk_edit.configuration_form_type_registry'
            $translator: '@translator'
            $typeChoices: '%asdoria_bulk_edit.form_configurations%'
        tags:
            - { name: form.type }
