services:
    Asdoria\SyliusBulkEditPlugin\MessageHandler\BulkEditMessageHandler:
        arguments:
            $entityManager: '@doctrine.orm.default_entity_manager'
            $actions: !tagged_iterator { tag: 'asdoria_bulk_edit.action', index_by: 'type' }
            $eventDispatcher: '@event_dispatcher'
        tags:
            -   name: messenger.message_handler
                handles: Asdoria\SyliusBulkEditPlugin\Message\BulkEditNotificationInterface
