services:
    asdoria_bulk_edit.action.enable_taxon:
        class: Asdoria\SyliusBulkEditPlugin\Action\Taxon\EnableTaxonAction
        public: true
        tags:
            -   name: asdoria_bulk_edit.action
                type: !php/const Asdoria\SyliusBulkEditPlugin\Action\Taxon\EnableTaxonAction::ENABLE_TAXON
                type_identifier: !php/const Asdoria\SyliusBulkEditPlugin\Action\ResourceActionInterface::TAXON_CONTEXT
                label: asdoria_bulk_edit.form.enable_taxon
                label_group: 'asdoria_bulk_edit.ui.label_group.taxons'
                form_type: Asdoria\SyliusBulkEditPlugin\Form\Type\Configuration\EnableConfigurationType
                
    asdoria_bulk_edit.action.parent_taxon:
        class: Asdoria\SyliusBulkEditPlugin\Action\Taxon\SetParentTaxonAction
        public: true
        calls:
            - [ setTaxonRepository, [ '@sylius.repository.taxon' ] ]
        tags:
            -   name: asdoria_bulk_edit.action
                type: !php/const Asdoria\SyliusBulkEditPlugin\Action\Taxon\SetParentTaxonAction::SET_PARENT_TAXON
                type_identifier: !php/const Asdoria\SyliusBulkEditPlugin\Action\ResourceActionInterface::TAXON_CONTEXT
                label: asdoria_bulk_edit.form.set_parent_taxon
                label_group: 'asdoria_bulk_edit.ui.label_group.taxons'
                form_type: Asdoria\SyliusBulkEditPlugin\Form\Type\Configuration\TaxonConfigurationType
