sylius_grid:
    grids:
        asdoria_bulk_edit_admin_product_variant:
            driver:
                name: doctrine/orm
                options:
                    class: '%sylius.model.product_variant.class%'
            limits: [ 50, 100, 200, 500 ]
            fields:
                id:
                    type: twig
                    label: sylius.ui.details
                    sortable: ~
                    path: .
                    options:
                        template: "@AsdoriaSyliusBulkEditPlugin/Admin/Grid/Field/ProductVariant/details.html.twig"
            filters:
                search:
                    type: string
                    label: sylius.ui.search
                    options:
                        fields: [ code, id ]
                product:
                    type: resource_autocomplete
                    label: sylius.ui.product
                    form_options:
                        resource: sylius.product
                        choice_name: descriptor
                        choice_value: code
                        multiple: true
                        remote_path: sylius_admin_ajax_products_by_phrase
                        load_edit_path: sylius_admin_ajax_product_by_code
                    options:
                        fields: [product.code]
                taxCategory:
                    type: entity
                    label: sylius.ui.tax_category
                    options:
                        fields: [ taxCategory ]
                    form_options:
                        class: "%sylius.model.tax_category.class%"
                        choice_label: name
            actions:
                bulk:
                    selected:
                        type: selected
                        label: asdoria_bulk_edit.ui.selected_taxon
                        options:
                            link:
                                route: asdoria_bulk_edit_admin_product_variant_bulk_edit
                                parameters:
                                    criteria: "expr:service('request_stack').getCurrentRequest().get('criteria', [])"
                                    context: "product_variant"
