sylius_grid:
    grids:
        asdoria_bulk_edit_admin_customer:
            driver:
                name: doctrine/orm
                options:
                    class: '%sylius.model.customer.class%'
            limits: [ 50, 100, 200, 500 ]
            fields:
                id:
                    type: twig
                    label: sylius.ui.details
                    sortable: ~
                    path: .
                    options:
                        template: "@AsdoriaSyliusBulkEditPlugin/Admin/Grid/Field/Customer/details.html.twig"
            filters:
                search:
                    type: string
                    label: sylius.ui.search
                    options:
                        fields: [ code, id ]
                customerGroup:
                    type: entity
                    label: sylius.ui.customer
                    options:
                        fields: [ customerGroup ]
                    form_options:
                        class: "%sylius.model.customer.class%"
                        choice_label: fullname
            actions:
                bulk:
                    selected:
                        type: selected
                        label: asdoria_bulk_edit.ui.selected_customer
                        options:
                            link:
                                route: asdoria_bulk_edit_admin_customer_bulk_edit
                                parameters:
                                    criteria: "expr:service('request_stack').getCurrentRequest().get('criteria', [])"
                                    context: "customer"
