asdoria_bulk_edit_admin_ajax_product_index:
    path: /products
    methods: [GET]
    defaults:
        _controller: sylius.controller.product::indexAction
        _sylius:
            template: "@AsdoriaSyliusBulkEditPlugin/Admin/Grid/Body/_rows.html.twig"
            grid: asdoria_bulk_edit_admin_product
    options:
        expose: true
