services:
    asdoria_bulk_edit.action.enable_product_variant:
        class: Asdoria\SyliusBulkEditPlugin\Action\ProductVariant\EnableProductVariantAction
        public: true
        tags:
            -   name: asdoria_bulk_edit.action
                type: !php/const Asdoria\SyliusBulkEditPlugin\Action\ProductVariant\EnableProductVariantAction::ENABLE_PRODUCT_VARIANT
                type_identifier: !php/const Asdoria\SyliusBulkEditPlugin\Action\ResourceActionInterface::PRODUCT_VARIANT_CONTEXT
                label: asdoria_bulk_edit.form.enable_product_variant
                label_group: 'asdoria_bulk_edit.ui.label_group.product_variants'
                form_type: Asdoria\SyliusBulkEditPlugin\Form\Type\Configuration\EnableConfigurationType
                
    asdoria_bulk_edit.action.tracked_product_variant:
        class: Asdoria\SyliusBulkEditPlugin\Action\ProductVariant\TrackedProductVariantAction
        public: true
        tags:
            -   name: asdoria_bulk_edit.action
                type: !php/const Asdoria\SyliusBulkEditPlugin\Action\ProductVariant\TrackedProductVariantAction::TRACKED_PRODUCT_VARIANT
                type_identifier: !php/const Asdoria\SyliusBulkEditPlugin\Action\ResourceActionInterface::PRODUCT_VARIANT_CONTEXT
                label: asdoria_bulk_edit.form.tracked_product_variant
                label_group: 'asdoria_bulk_edit.ui.label_group.product_variants'
                form_type: Asdoria\SyliusBulkEditPlugin\Form\Type\Configuration\EnableConfigurationType
                
    asdoria_bulk_edit.action.property_product_variant:
        class: Asdoria\SyliusBulkEditPlugin\Action\ProductVariant\PropertyProductVariantAction
        public: true
        tags:
            -   name: asdoria_bulk_edit.action
                type: !php/const Asdoria\SyliusBulkEditPlugin\Action\ProductVariant\PropertyProductVariantAction::PROPERTY_PRODUCT_VARIANT
                type_identifier: !php/const Asdoria\SyliusBulkEditPlugin\Action\ResourceActionInterface::PRODUCT_VARIANT_CONTEXT
                label: asdoria_bulk_edit.form.property_product_variant
                label_group: 'asdoria_bulk_edit.ui.label_group.product_variants'
                form_type: Asdoria\SyliusBulkEditPlugin\Form\Type\Configuration\PropertyConfigurationType
