asdoria_bulk_edit_admin_product_variant_index:
    path: /product-variants
    methods: [ GET, POST ]
    defaults:
        _controller: sylius.controller.product_variant::indexAction
        _sylius:
            section: admin
            permission: true
            event: bulk_edit
            grid: asdoria_bulk_edit_admin_product_variant
            template: '@AsdoriaSyliusBulkEditPlugin/Admin/BulkEdit/index.html.twig'
            vars:
                icon: outdent
                scroll_route: asdoria_bulk_edit_admin_ajax_product_variant_index
