asdoria_bulk_edit_admin_taxon_index:
    path: /taxons
    methods: [ GET, POST ]
    defaults:
        _controller: sylius.controller.taxon::indexAction
        _sylius:
            section: admin
            permission: true
            event: bulk_edit
            grid: asdoria_bulk_edit_admin_taxon
            template: '@AsdoriaSyliusBulkEditPlugin/Admin/BulkEdit/index.html.twig'
            vars:
                icon: list alternate outline
                scroll_route: asdoria_bulk_edit_admin_ajax_taxon_index
